export default {
  // Vendored normalize.css includes deliberate browser compatibility rules.
  ignoreFiles: ['src/scss/base/_normalize.scss'],
  extends: ['stylelint-config-standard-scss'],

  plugins: ['stylelint-order'],

  rules: {
    'selector-class-pattern': '^[a-z][a-z0-9]*(?:[-_]+[a-z0-9]+)*$',
    'order/properties-order': [
      [
        'content',
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'z-index',
        'display',
        'visibility',
        'overflow',
        'box-sizing',
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        'font',
        'font-family',
        'font-size',
        'font-weight',
        'line-height',
        'text-align',
        'text-decoration',
        'text-transform',
        'letter-spacing',
        'color',
        'background',
        'background-color',
        'background-image',
        'background-position',
        'background-size',
        'border',
        'border-radius',
        'opacity',
        'transform',
        'transition',
        'cursor',
        'pointer-events',
      ],
    ],
  },
};
